export const PLAYER_ADDED = 'PLAYER_ADDED';
export const PLAYER_REMOVED = 'PLAYER_REMOVED';
export const GAME_CREATED = 'GAME_CREATED';
export const HOLE_UPDATED = 'HOLE_UPDATED';
export const COURSE_ADDED = 'COURSE_ADDED';
export const SCORE_UPDATED = 'SCORE_UPDATED';
export const GAME_REMOVED = 'GAME_REMOVED';
export const CURRENT_GAME_CHANGED = 'CURRENT_GAME_CHANGED';
